// <Auto-Generated></Auto-Generated>

#if NET6_0_OR_GREATER
namespace System
{
    internal static class SharedRandom
    {
        public static Random Shared => Random.Shared;
    }
}
#else

using System.Threading;
namespace System
{
    internal static class SharedRandom
    {
        private static readonly ThreadLocal<Random> s_random = new(() => new(), false);

        public static Random Shared => s_random.Value!;
    }
}
#endif