// <Auto-Generated></Auto-Generated>

#if NET6_0_OR_GREATER
namespace System;

internal static class SharedRandom
{
    public static Random Shared => Random.Shared;
}
#else

using System.Threading;
namespace System
/* 项目“Cuture.Http (net6.0)”的未合并的更改
在此之前:
    internal static class SharedRandom
在此之后:
internal static class SharedRandom
*/
;

internal static class SharedRandom
{
    private static readonly ThreadLocal<Random> s_random = new(() => new(), false);

    public static Random Shared => s_random.Value!;

/* 项目“Cuture.Http (net6.0)”的未合并的更改
在此之前:
    }
在此之后:
}
*/
}
#endif